"""Generate pytest modules from Stacksmith YAML test manifests."""

from dataclasses import dataclass
from pprint import pformat

from ..models import StacksmithTestManifest, render_file_reference


@dataclass(frozen=True)
class GeneratedPytestModule:
    """Generated pytest source text and metadata."""

    source: str
    test_count: int


class StacksmithTestGenerator:
    """Compile a Stacksmith test manifest into executable pytest source code."""

    def __init__(self, manifest: StacksmithTestManifest) -> None:
        self._manifest = manifest

    def generate_pytest_module(self) -> GeneratedPytestModule:
        """Generate a pytest module from the configured test manifest.

        Returns:
            A generated pytest source payload and total number of generated tests.
        """
        lines = [
            '"""Generated by `stacksmith test`; do not edit by hand."""',
            "",
            "import runpy",
            "",
            "import pytest",
            "from stacksmith.validations.outcomes import InputValidationOutcome, PlanValidationOutcome",
            "",
        ]

        if self._manifest.fixtures is not None:
            lines.extend(self._render_fixture_helpers())

        test_count = 0
        test_count += self._render_variable_policy_tests(lines)
        test_count += self._render_plan_policy_tests(lines)
        test_count += self._render_component_property_tests(lines)

        return GeneratedPytestModule(
            source="\n".join(lines).rstrip() + "\n", test_count=test_count
        )

    def _render_fixture_helpers(self) -> list[str]:
        fixtures = self._manifest.fixtures
        fixture_mode = fixtures.mode if fixtures is not None else "per-suite"
        fixture_scope = "module" if fixture_mode == "per-suite" else "function"
        fixture_lines = [
            "_STACKSMITH_FIXTURE_STATE: dict[str, object] = {}",
            "",
            "def _run_fixture(inline_code: str | None, script_path: str | None, origin: str) -> None:",
            '    namespace = {"fixture_state": _STACKSMITH_FIXTURE_STATE}',
            "    if inline_code is not None:",
            '        exec(compile(inline_code, origin, "exec"), namespace)  # noqa: S102',
            "        return",
            "    if script_path is None:",
            "        return",
            "    loaded = runpy.run_path(script_path, init_globals=namespace)",
            '    runner = loaded.get("run")',
            "    if callable(runner):",
            "        runner(state=_STACKSMITH_FIXTURE_STATE)",
            "",
            f'@pytest.fixture(scope="{fixture_scope}", autouse=True)',
            "def _stacksmith_generated_fixtures() -> None:",
        ]

        setup_inline, setup_script = self._fixture_source_values("setup")
        teardown_inline, teardown_script = self._fixture_source_values("teardown")
        fixture_lines.extend(
            [
                "    _STACKSMITH_FIXTURE_STATE.clear()",
                "    _run_fixture(",
                f"        inline_code={setup_inline},",
                f"        script_path={setup_script},",
                '        origin="fixtures.setup",',
                "    )",
                "    yield",
                "    _run_fixture(",
                f"        inline_code={teardown_inline},",
                f"        script_path={teardown_script},",
                '        origin="fixtures.teardown",',
                "    )",
                "    _STACKSMITH_FIXTURE_STATE.clear()",
                "",
            ]
        )
        return fixture_lines

    def _fixture_source_values(self, fixture_name: str) -> tuple[str, str]:
        fixtures = self._manifest.fixtures
        if fixtures is None:
            return "None", "None"

        fixture = getattr(fixtures, fixture_name)
        if fixture is None:
            return "None", "None"

        if fixture.inline is not None:
            return repr(fixture.inline), "None"

        script_reference = fixture.script
        if script_reference is None:
            return "None", "None"
        return "None", repr(render_file_reference(script_reference))

    def _render_variable_policy_tests(self, lines: list[str]) -> int:
        count = 0
        for policy_name, cases in self._manifest.variable_policies.items():
            for index, case in enumerate(cases):
                function_name = self._function_name(
                    "variable",
                    policy_name,
                    case.name,
                    index,
                )
                lines.append(f"def {function_name}(stacksmith_test_runner) -> None:")
                self._append_assignment(lines, "value", case.value)
                lines.append(
                    "    outcome, _ = stacksmith_test_runner.run_variable_policy("
                    f"{policy_name!r}, value)"
                )
                lines.append(
                    "    assert outcome == "
                    f"InputValidationOutcome.{case.expect.upper()}"
                )
                lines.append("")
                count += 1
        return count

    def _render_plan_policy_tests(self, lines: list[str]) -> int:
        count = 0
        for policy_name, cases in self._manifest.plan_policies.items():
            for index, case in enumerate(cases):
                function_name = self._function_name(
                    "plan", policy_name, case.name, index
                )
                lines.append(f"def {function_name}(stacksmith_test_runner) -> None:")
                payload = (
                    case.plan
                    if case.plan is not None
                    else {
                        "resource_changes": [
                            resource.to_plan_change()
                            for resource in case.resources or []
                        ]
                    }
                )
                self._append_assignment(lines, "plan_payload", payload)
                if case.context:
                    self._append_assignment(lines, "context", case.context)
                    lines.append(
                        "    outcome, _ = stacksmith_test_runner.run_plan_policy("
                        f"{policy_name!r}, plan_payload, context=context)"
                    )
                else:
                    lines.append(
                        "    outcome, _ = stacksmith_test_runner.run_plan_policy("
                        f"{policy_name!r}, plan_payload)"
                    )
                lines.append(
                    "    assert outcome == "
                    f"PlanValidationOutcome.{case.expect.upper()}"
                )
                lines.append("")
                count += 1
        return count

    def _render_component_property_tests(self, lines: list[str]) -> int:
        count = 0
        for component_type, properties in self._manifest.component_properties.items():
            for property_name, cases in properties.items():
                for index, case in enumerate(cases):
                    function_name = self._function_name(
                        "property",
                        f"{component_type}_{property_name}",
                        case.name,
                        index,
                    )
                    lines.append(
                        f"def {function_name}(stacksmith_test_runner) -> None:"
                    )
                    self._append_assignment(lines, "value", case.value)
                    self._append_assignment(lines, "inputs", case.inputs)
                    lines.append(
                        "    result = stacksmith_test_runner.run_component_property("
                        f"{component_type!r}, {property_name!r}, value, inputs=inputs)"
                    )
                    self._append_assignment(lines, "expected_value", case.expect.value)
                    lines.append("    assert result.value == expected_value")
                    if case.expect.output_name is not None:
                        lines.append(
                            "    assert result.output_name == "
                            f"{case.expect.output_name!r}"
                        )
                    lines.append("")
                    count += 1
        return count

    def _append_assignment(self, lines: list[str], name: str, value: object) -> None:
        literal = pformat(value, sort_dicts=True, width=88)
        if "\n" not in literal:
            lines.append(f"    {name} = {literal}")
            return

        lines.append(f"    {name} = (")
        lines.extend(f"        {line}" for line in literal.splitlines())
        lines.append("    )")

    def _function_name(
        self,
        prefix: str,
        scope: str,
        case_name: str | None,
        index: int,
    ) -> str:
        normalized_scope = self._sanitize_identifier(scope)
        normalized_case = (
            self._sanitize_identifier(case_name)
            if case_name is not None
            else f"case_{index + 1}"
        )
        return f"test_{prefix}_{normalized_scope}_{normalized_case}"

    def _sanitize_identifier(self, value: str) -> str:
        sanitized = "".join(
            char.lower() if char.isalnum() else "_" for char in value.strip()
        )
        while "__" in sanitized:
            sanitized = sanitized.replace("__", "_")
        return sanitized.strip("_") or "case"
