name: gitops-platform-example
components:
  app_ec2_instance:
    type: aws_ec2_instance
    properties:
      name: app-writer
      create_iam_instance_profile: true
      create_security_group: true
      metadata_options:
        http_tokens: required
        http_endpoint: enabled
      monitoring: true
  assets_bucket:
    type: aws_s3_bucket
    properties:
      versioning_enabled: true
      block_public_acls: false
      block_public_policy: true
      ignore_public_acls: true
      restrict_public_buckets: true
      control_object_ownership: true
      object_ownership: BucketOwnerEnforced
      attach_deny_insecure_transport_policy: true
